services:
  app:
    build: .
    container_name: laravel_app
    ports:
      - "4567:4567"
    volumes:
      - .:/var/www:cached
      - /var/www/node_modules
      - /var/www/vendor
    extra_hosts:
      - "host.docker.internal:host-gateway"
